name: Deploy Frontend to Azure Web App - wa-drogerie-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure using Managed Identity
        uses: azure/login@v2
        with:
          managed-identity-client-id: 2a1a8c5d-2e8e-4b25-8bce-cff17634fa4c # Deine Managed Identity Client ID

      - name: Deploy HTML file to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wa-drogerie-app'
          slot-name: 'Production'
          package: './Frontend/Frontend.html' # Pfad zur HTML-Datei
